"""create user table

Revision ID: b2413e05c120
Revises: 823a1fffe421
Create Date: 2018-02-25 20:31:16.833894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2413e05c120'
down_revision = '823a1fffe421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
